services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file: [.env]
    depends_on: [db]
    ports:
      - ${API_PORT}:8080
    restart: always
  db:
    image: postgres:16
    restart: always
    env_file: [.env]
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: