services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file: [.env]
    environment:
      DB_URL: ${DB_URL}
    depends_on: [db]
    restart: always
  db:
    image: postgres:16
    restart: always
    env_file: [.env]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: