services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5433
volumes:
  pgdata: