spring:
  application:
    name: library
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  file:
    name: app.log
  com:
    example: trace
  level:
    org:
      springframework:
        security: info
