spring:
  application:
    name: Demo Jpa
  datasource:
    url: ${DB_URL}
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  logging:
    level:
      org:
        springframework:
          security:
            trace: true
