spring:
  application:
    name: library-api
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
logging:
  file:
    name: app.log
  com:
    example: trace
  level:
    org:
      springframework:
        security: info
---
# dev profile
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL_DEV}
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

---
# prod profile
spring:
  config:
    activate:
      on-profile: prod
logging:
  file:
    name: app.log
